export declare const ENDPOINTS: {
    readonly ping: "/api/v1/ping";
    readonly credentials: "/api/v1/credentials";
    readonly credentialById: (id: string) => string;
    readonly documentStores: "/api/v1/document-store/store";
    readonly documentStoreById: (id: string) => string;
    readonly documentStoreUpsert: (id: string) => string;
    readonly documentStoreRefresh: (id: string) => string;
    readonly docstoreLoaderSave: "/api/v1/document-store/loader/save";
    readonly docstoreLoaderProcess: (loaderId: string) => string;
    readonly docstoreLoaderPreview: "/api/v1/document-store/loader/preview";
    readonly docstoreLoaderDelete: (storeId: string, loaderId: string) => string;
    readonly docstoreChunksList: (storeId: string, fileId: string, pageNo: number) => string;
    readonly docstoreChunkUpdate: (storeId: string, loaderId: string, chunkId: string) => string;
    readonly docstoreChunkDelete: (storeId: string, loaderId: string, chunkId: string) => string;
    readonly vectorstoreQuery: "/api/v1/document-store/vectorstore/query";
    readonly vectorstoreSave: "/api/v1/document-store/vectorstore/save";
    readonly vectorstoreInsert: "/api/v1/document-store/vectorstore/insert";
    readonly vectorstoreUpdate: "/api/v1/document-store/vectorstore/update";
    readonly vectorstoreDelete: (storeId: string) => string;
    readonly docstoreComponentsLoaders: "/api/v1/document-store/components/loaders";
    readonly docstoreComponentsEmbeddings: "/api/v1/document-store/components/embeddings";
    readonly docstoreComponentsVectorstore: "/api/v1/document-store/components/vectorstore";
    readonly docstoreComponentsRecordManager: "/api/v1/document-store/components/recordmanager";
    readonly chatflows: "/api/v1/chatflows";
    readonly chatflowById: (id: string) => string;
    readonly chatflowByApiKey: (apikey: string) => string;
    readonly nodes: "/api/v1/nodes";
    readonly nodeByName: (name: string) => string;
    readonly nodesByCategory: (category: string) => string;
    readonly prediction: (chatflowId: string) => string;
    readonly vectorUpsert: (chatflowId: string) => string;
    readonly attachments: (chatflowId: string) => string;
    readonly docstoreGenerateToolDesc: (id: string) => string;
    readonly variables: "/api/v1/variables";
    readonly variableById: (id: string) => string;
    readonly customTools: "/api/v1/tools";
    readonly customToolById: (id: string) => string;
    readonly assistants: "/api/v1/assistants";
    readonly assistantById: (id: string) => string;
    readonly chatMessages: (chatflowId: string) => string;
    readonly chatMessagesAbort: (chatflowId: string, chatId: string) => string;
    readonly upsertHistory: (chatflowId: string) => string;
    readonly upsertHistoryRoot: "/api/v1/upsert-history";
};
//# sourceMappingURL=endpoints.d.ts.map